name: Build LaTeX

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Build PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          extra_system_packages: |
            latexmk
            babel-italian
            csquotes
            biblatex
            biber
            amsmath
            amsfonts
            amssymb
            mathtools
            siunitx
            cleveref
            pgf
            pgfplots
            tikz
          post_compile: |
            mv build/main.pdf build/appunti-meccanica-quantistica.pdf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: appunti-meccanica-quantistica-pdf
          path: build/appunti-meccanica-quantistica.pdf
