name: Build LaTeX

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup TeX Live
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          
      - name: Build PDF
        run: |
          mkdir -p build
          latexmk -pdf -quiet main.tex
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: appunti-pdf
          path: build/main.pdf
