name: Build LaTeX

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:

permissions:
  contents: write

jobs:
  build:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Compile with LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          post_compile: |
            mv build/main.pdf build/appunti-meccanica-quantistica.pdf

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: appunti-meccanica-quantistica-pdf
          path: build/appunti-meccanica-quantistica.pdf

  release:
    name: Create Release on tag
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download built PDF artifact
        uses: actions/download-artifact@v4
        with:
          name: appunti-meccanica-quantistica-pdf
          path: dist

      - name: Publish GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          artifacts: dist/appunti-meccanica-quantistica.pdf
          artifactContentType: application/pdf
          allowUpdates: true
          generateReleaseNotes: true

