name: Build LaTeX

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup TeX Live
        uses: dante-ev/texlive-action@v2
        with:
          profile: scheme-small
          packages: |
            latexmk
            babel-italian
            csquotes
            biblatex
            biber
            amsmath
            amsfonts
            amssymb
            mathtools
            siunitx
            cleveref
            pgf
            pgfplots
            tikz
      - name: Build PDF
        run: |
          latexmk -pdf -quiet main.tex
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: appunti-pdf
          path: build/main.pdf
